### ISSUE TITLE
New update call in 4.1

### ISSUE THREAD

**Issue by szepeviktor** [mpsparrow/disable-updates-manager#55]
Are you aware of these two *new* calls?

https://github.com/WordPress/WordPress/commit/b0a2416040f24dcf0f50b3520dfc798de43a904a

**Comment by szepeviktor** [comment]
@mpsparrow Why don't you copy my 3 functions?
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-disable-updates/disable-updates.php#L162-L206

**Comment by mpsparrow** [comment]
We are working on completely redoing the plugin from scratch. I have teamed up with ronalfy (https://github.com/ronalfy). Currently me are just starting the coding stage. If you want to contribute check out the repo. https://github.com/disableupdatespluginproject/Easy-Updates-Manager

**Comment by szepeviktor** [comment]
I could gladly help at the design stage, not that much at correting design defects.
